# Generated by Django 2.1.7 on 2019-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180924_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pageitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_flag', models.ImageField(upload_to='images')),
                ('lang_flag_pl', models.ImageField(null=True, upload_to='images')),
                ('lang_flag_en', models.ImageField(null=True, upload_to='images')),
                ('headtitle', models.CharField(max_length=200)),
                ('headtitle_pl', models.CharField(max_length=200, null=True)),
                ('headtitle_en', models.CharField(max_length=200, null=True)),
                ('mainpage', models.CharField(max_length=200)),
                ('mainpage_pl', models.CharField(max_length=200, null=True)),
                ('mainpage_en', models.CharField(max_length=200, null=True)),
                ('news', models.CharField(max_length=200)),
                ('news_pl', models.CharField(max_length=200, null=True)),
                ('news_en', models.CharField(max_length=200, null=True)),
                ('blog', models.CharField(max_length=200)),
                ('blog_pl', models.CharField(max_length=200, null=True)),
                ('blog_en', models.CharField(max_length=200, null=True)),
                ('download', models.CharField(max_length=200)),
                ('download_pl', models.CharField(max_length=200, null=True)),
                ('download_en', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=200)),
                ('contact_pl', models.CharField(max_length=200, null=True)),
                ('contact_en', models.CharField(max_length=200, null=True)),
                ('send_email', models.CharField(max_length=200)),
                ('send_email_pl', models.CharField(max_length=200, null=True)),
                ('send_email_en', models.CharField(max_length=200, null=True)),
                ('login', models.CharField(blank=True, max_length=200, null=True)),
                ('login_pl', models.CharField(blank=True, max_length=200, null=True)),
                ('login_en', models.CharField(blank=True, max_length=200, null=True)),
                ('logout', models.CharField(max_length=200)),
                ('logout_pl', models.CharField(max_length=200, null=True)),
                ('logout_en', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_pl', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('summary', models.TextField()),
                ('summary_pl', models.TextField(null=True)),
                ('summary_en', models.TextField(null=True)),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='link',
        ),
        migrations.AddField(
            model_name='tech',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tech',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tech',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AddField(
            model_name='tech',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tech',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
