# Generated by Django 2.1.7 on 2019-07-18 13:39

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190717_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['-pubdate']},
        ),
        migrations.AlterModelOptions(
            name='trick',
            options={'ordering': ['-pubdate']},
        ),
        migrations.AddField(
            model_name='tech',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 13, 39, 6, 30209, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trick',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tech',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
