# Generated by Django 2.1.7 on 2019-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190718_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='myphoto',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='myphoto_en',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='myphoto_pl',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
