# Generated by Django 2.1.7 on 2019-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20190731_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='about_me',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='about_me_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='about_me_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='authphoto',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='authphoto_en',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='authphoto_pl',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
