# Generated by Django 2.1.7 on 2019-07-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20190731_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='login_to_see',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_to_see_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='login_to_see_pl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
