# Generated by Django 2.1.7 on 2019-07-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20190731_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='re_password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='register',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageitem',
            name='username',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
