# Generated by Django 2.1.1 on 2018-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
