# Generated by Django 2.1.7 on 2019-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
