# Generated by Django 2.1.7 on 2019-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_pl', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('readme', models.TextField()),
                ('readme_pl', models.TextField(null=True)),
                ('readme_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('image_pl', models.ImageField(null=True, upload_to='images')),
                ('image_en', models.ImageField(null=True, upload_to='images')),
                ('version', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=25)),
                ('compatible', models.CharField(max_length=200)),
                ('compatible_pl', models.CharField(max_length=200, null=True)),
                ('compatible_en', models.CharField(max_length=200, null=True)),
                ('downlink', models.TextField()),
                ('gitsrccode', models.TextField(blank=True)),
                ('license', models.CharField(blank=True, max_length=250)),
                ('license_pl', models.CharField(blank=True, max_length=250, null=True)),
                ('license_en', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_intro', models.CharField(max_length=50)),
                ('big_intro_pl', models.CharField(max_length=50, null=True)),
                ('big_intro_en', models.CharField(max_length=50, null=True)),
                ('small_intro', models.CharField(max_length=300)),
                ('small_intro_pl', models.CharField(max_length=300, null=True)),
                ('small_intro_en', models.CharField(max_length=300, null=True)),
                ('send_email', models.CharField(max_length=30)),
                ('send_email_pl', models.CharField(max_length=30, null=True)),
                ('send_email_en', models.CharField(max_length=30, null=True)),
                ('published', models.CharField(max_length=30)),
                ('published_pl', models.CharField(max_length=30, null=True)),
                ('published_en', models.CharField(max_length=30, null=True)),
                ('version', models.CharField(max_length=20)),
                ('version_pl', models.CharField(max_length=20, null=True)),
                ('version_en', models.CharField(max_length=20, null=True)),
                ('system', models.CharField(max_length=20)),
                ('system_pl', models.CharField(max_length=20, null=True)),
                ('system_en', models.CharField(max_length=20, null=True)),
                ('weight', models.CharField(max_length=25)),
                ('weight_pl', models.CharField(max_length=25, null=True)),
                ('weight_en', models.CharField(max_length=25, null=True)),
                ('license', models.CharField(max_length=25)),
                ('license_pl', models.CharField(max_length=25, null=True)),
                ('license_en', models.CharField(max_length=25, null=True)),
                ('download_exe', models.CharField(max_length=200)),
                ('download_exe_pl', models.CharField(max_length=200, null=True)),
                ('download_exe_en', models.CharField(max_length=200, null=True)),
                ('link_git', models.CharField(max_length=200)),
                ('link_git_pl', models.CharField(max_length=200, null=True)),
                ('link_git_en', models.CharField(max_length=200, null=True)),
                ('details', models.CharField(max_length=25)),
                ('details_pl', models.CharField(max_length=25, null=True)),
                ('details_en', models.CharField(max_length=25, null=True)),
                ('launch_new', models.CharField(max_length=40)),
                ('launch_new_pl', models.CharField(max_length=40, null=True)),
                ('launch_new_en', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
