# Generated by Django 2.1.1 on 2018-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotto',
            name='gitsrccode',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lotto',
            name='license',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
