# Generated by Django 2.1.7 on 2019-07-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprograms', '0002_myprogram_linkinside'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myprogram',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='myprogram',
            name='place',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
