# Generated by Django 2.1.7 on 2019-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprograms', '0005_randomizeritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizeritems',
            name='sel2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='randomizeritems',
            name='sel2_pl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
