# Generated by Django 2.1.7 on 2019-07-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprograms', '0006_auto_20190718_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomizeritems',
            old_name='save',
            new_name='saveme',
        ),
        migrations.RenameField(
            model_name='randomizeritems',
            old_name='save_en',
            new_name='saveme_en',
        ),
        migrations.RenameField(
            model_name='randomizeritems',
            old_name='save_pl',
            new_name='saveme_pl',
        ),
    ]
