# Generated by Django 2.1.1 on 2018-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('N1', models.IntegerField()),
                ('N2', models.IntegerField()),
                ('N3', models.IntegerField()),
                ('N4', models.IntegerField()),
                ('N5', models.IntegerField()),
                ('N6', models.IntegerField()),
                ('N7', models.IntegerField()),
                ('N8', models.IntegerField()),
                ('N9', models.IntegerField()),
                ('N10', models.IntegerField()),
                ('N11', models.IntegerField()),
                ('N12', models.IntegerField()),
                ('N13', models.IntegerField()),
                ('N14', models.IntegerField()),
                ('N15', models.IntegerField()),
                ('N16', models.IntegerField()),
                ('N17', models.IntegerField()),
                ('N18', models.IntegerField()),
                ('N19', models.IntegerField()),
                ('N20', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('N1', models.IntegerField()),
                ('N2', models.IntegerField()),
                ('N3', models.IntegerField()),
                ('N4', models.IntegerField()),
                ('N5', models.IntegerField()),
                ('N6', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('N1', models.IntegerField()),
                ('N2', models.IntegerField()),
                ('N3', models.IntegerField()),
                ('N4', models.IntegerField()),
                ('N5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('N1', models.IntegerField()),
                ('N2', models.IntegerField()),
                ('N3', models.IntegerField()),
                ('N4', models.IntegerField()),
                ('N5', models.IntegerField()),
                ('R1', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lotto',
            name='gitsrccode',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lotto',
            name='license',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
